[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
    '@chainlink/contracts-ccip=lib/chainlink-brownie-contracts/contracts',
    '@t-rex/contracts=lib/T-REX/contracts',
    'forge-std=lib/forge-std/src'
]
auto_detect_remappings = true
optimizer = true
optimizer_runs = 200
via_ir = true
solc_version = "0.8.24"

[rpc_endpoints]
ethereum = "https://eth-mainnet.alchemyapi.io/v2/${ALCHEMY_API_KEY}"
ethereum_sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"
base_goerli = "https://goerli.base.org"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
